export const REQUESTED_FETCH_CLIENT_PREFERENCE =
  'REQUESTED_FETCH_CLIENT_PREFERENCE';

export const SUCCESS_FETCH_CLIENT_PREFERENCE =
  'SUCCESS_FETCH_CLIENT_PREFERENCE';

export const FAILED_FETCH_CLIENT_PREFERENCE = 'FAILED_FETCH_CLIENT_PREFERENCE';

export const LOGIN_USER_REQUESTED = 'LOGIN_USER_REQUESTED';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILED = 'LOGIN_USER_FAILED';
